'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiFetch } from '@/lib/api/fetcher';
import { RotiRequirement, Commitment } from '@/types';
import { Button } from '@/components/ui/button';
import { StatusBadge } from '@/components/shared/StatusBadge';
import { Download, FileText } from 'lucide-react';
import { format } from 'date-fns';
import { useAuthStore } from '@/stores/authStore';
import { toast } from 'sonner';

type CommitmentWithUser = Commitment & { userName?: string; userItsNumber?: string; userEmail?: string };

export default function AdminReportsPage() {
  const [selectedId, setSelectedId] = useState('');
  const { accessToken } = useAuthStore();

  const { data: reqRes } = useQuery({
    queryKey: ['requirements'],
    queryFn: () => apiFetch<RotiRequirement[]>('/api/v1/requirements'),
  });
  const { data: detailRes } = useQuery({
    queryKey: ['requirement-detail', selectedId],
    queryFn: () => apiFetch<RotiRequirement & { commitments: CommitmentWithUser[] }>(`/api/v1/requirements/${selectedId}`),
    enabled: !!selectedId,
  });

  const requirements = reqRes?.data || [];
  const detail = detailRes?.data;

  async function exportCSV() {
    const res = await fetch(`/api/v1/reports/requirements/${selectedId}/csv`, {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    if (!res.ok) { toast.error('Export failed'); return; }
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${detail?.title?.replace(/\s+/g, '-') || selectedId}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function exportPDF() {
    if (!detail) return;
    const jsPDF = (await import('jspdf')).default;
    const autoTable = (await import('jspdf-autotable')).default;
    const doc = new jsPDF({ orientation: 'landscape' });

    // Header
    doc.setFontSize(16);
    doc.setTextColor(74, 51, 0);
    doc.text('Faiz al-Mawaid al-Burhaniyah — Badri Mohallah Salmiya', 14, 18);

    doc.setFontSize(11);
    doc.setTextColor(92, 74, 26);
    doc.text(`Report: ${detail.title}`, 14, 27);
    doc.text(`Generated: ${format(new Date(), 'dd MMM yyyy HH:mm')}`, 14, 34);
    doc.text(`Delivery Date: ${format(new Date(detail.deliveryDate), 'dd MMM yyyy')}`, 14, 41);
    doc.text(
      `Packets Required: ${detail.totalPacketsRequired}   |   Committed: ${detail.totalCommitted || 0}   |   Commitments: ${detail.commitments?.length || 0}`,
      14, 48
    );

    // Divider line
    doc.setDrawColor(184, 150, 12);
    doc.setLineWidth(0.5);
    doc.line(14, 52, 283, 52);

    // Table — ITS Number is first column
    const rows = (detail.commitments || []).map(c => [
      (c as any).userItsNumber || '—',
      c.userName || '—',
      (c as any).userEmail || '—',
      String(c.packetsCommitted),
      c.status,
      format(new Date(c.createdAt), 'dd MMM yyyy'),
    ]);

    autoTable(doc, {
      startY: 56,
      head: [['ITS Number', 'Name', 'Email', 'Packets', 'Status', 'Submitted']],
      body: rows,
      headStyles: {
        fillColor: [184, 150, 12],
        textColor: [44, 31, 0],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: { fontSize: 8.5 },
      alternateRowStyles: { fillColor: [255, 253, 240] },
      columnStyles: {
        0: { cellWidth: 28 }, // ITS Number
        1: { cellWidth: 45 }, // Name
        2: { cellWidth: 55 }, // Email
        3: { cellWidth: 20, halign: 'center' }, // Packets
        4: { cellWidth: 28 }, // Status
        5: { cellWidth: 32 }, // Date
      },
    });

    // Footer on every page
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(7.5);
      doc.setTextColor(156, 138, 80);
      doc.text(
        `Generated by ROTI Management System — FMB Salmiya   |   Page ${i} of ${pageCount}`,
        14,
        doc.internal.pageSize.height - 8
      );
    }

    doc.save(`${detail.title.replace(/\s+/g, '-')}.pdf`);
  }

  return (
    <div className="space-y-5">
      <h2 className="text-xl font-bold" style={{ fontFamily: 'Amiri, serif', color: 'var(--brand-brown)', borderBottom: '1px solid var(--brand-gold-deep)', paddingBottom: '4px' }}>
        Reports & Exports
      </h2>

      <div className="bg-white rounded-xl border p-5 space-y-4" style={{ borderColor: 'var(--border-default)' }}>
        <div className="space-y-1">
          <label className="text-sm font-medium" style={{ color: 'var(--text-secondary)' }}>Select Requirement</label>
          <select value={selectedId} onChange={e => setSelectedId(e.target.value)}
            className="w-full max-w-sm border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm bg-white">
            <option value="">Choose a requirement…</option>
            {requirements.map(r => (
              <option key={r.id} value={r.id}>
                {r.title} — {format(new Date(r.deliveryDate), 'dd MMM yyyy')}
              </option>
            ))}
          </select>
        </div>

        {detail && (
          <>
            <div className="p-4 bg-[var(--brand-cream)] rounded-lg border" style={{ borderColor: 'var(--border-default)' }}>
              <p className="font-semibold" style={{ color: 'var(--brand-brown)' }}>{detail.title}</p>
              <div className="flex gap-4 mt-2 text-sm flex-wrap">
                <span style={{ color: 'var(--text-secondary)' }}>Required: <strong>{detail.totalPacketsRequired}</strong></span>
                <span style={{ color: 'var(--text-secondary)' }}>Committed: <strong style={{ color: 'var(--brand-gold-deep)' }}>{detail.totalCommitted || 0}</strong></span>
                <span style={{ color: 'var(--text-secondary)' }}>Commitments: <strong>{detail.commitments?.length || 0}</strong></span>
                <StatusBadge status={detail.status} />
              </div>
              <p className="text-xs mt-2" style={{ color: 'var(--text-muted)' }}>
                Both exports include: ITS Number, Name, Email, Packets, Status, Submission Date
              </p>
            </div>

            <div className="flex gap-3 flex-wrap">
              <Button onClick={exportCSV} variant="outline" className="border-[var(--border-default)] text-[var(--brand-brown)]">
                <Download size={16} className="mr-1" /> Export Excel/CSV
              </Button>
              <Button onClick={exportPDF} className="font-semibold" style={{ background: 'var(--brand-gold)', color: 'var(--text-on-gold)' }}>
                <FileText size={16} className="mr-1" /> Export PDF
              </Button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
