'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiFetch } from '@/lib/api/fetcher';
import { RotiRequirement, Commitment } from '@/types';
import { Button } from '@/components/ui/button';
import { StatusBadge } from '@/components/shared/StatusBadge';
import { Download, FileText } from 'lucide-react';
import { format } from 'date-fns';
import { useAuthStore } from '@/stores/authStore';
import { toast } from 'sonner';

export default function AdminReportsPage() {
  const [selectedId, setSelectedId] = useState('');
  const { accessToken } = useAuthStore();

  const { data: reqRes } = useQuery({ queryKey: ['requirements'], queryFn: () => apiFetch<RotiRequirement[]>('/api/v1/requirements') });
  const { data: detailRes } = useQuery({
    queryKey: ['requirement-detail', selectedId],
    queryFn: () => apiFetch<RotiRequirement & { commitments: (Commitment & { userName?: string })[] }>(`/api/v1/requirements/${selectedId}`),
    enabled: !!selectedId,
  });

  const requirements = reqRes?.data || [];
  const detail = detailRes?.data;

  async function exportCSV() {
    const res = await fetch(`/api/v1/reports/requirements/${selectedId}/csv`, {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    if (!res.ok) { toast.error('Export failed'); return; }
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `report-${selectedId}.csv`; a.click();
    URL.revokeObjectURL(url);
  }

  async function exportPDF() {
    if (!detail) return;
    const jsPDF = (await import('jspdf')).default;
    const autoTable = (await import('jspdf-autotable')).default;
    const doc = new jsPDF();

    doc.setFontSize(16);
    doc.setTextColor(74, 51, 0);
    doc.text('Faiz al-Mawaid al-Burhaniyah — Badri Mohallah Salmiya', 14, 20);
    doc.setFontSize(12);
    doc.text(`Report: ${detail.title}`, 14, 30);
    doc.text(`Date: ${format(new Date(), 'dd MMM yyyy')}`, 14, 38);
    doc.text(`Delivery: ${format(new Date(detail.deliveryDate), 'dd MMM yyyy')}`, 14, 46);
    doc.text(`Required: ${detail.totalPacketsRequired} | Committed: ${detail.totalCommitted || 0}`, 14, 54);

    const rows = (detail.commitments || []).map(c => [
      c.userName || '—', c.packetsCommitted, c.status, format(new Date(c.createdAt), 'dd MMM yyyy'),
      c.adminRating || '—', c.adminFeedback || '—',
    ]);

    autoTable(doc, {
      startY: 64,
      head: [['Mumineen', 'Packets', 'Status', 'Date', 'Rating', 'Feedback']],
      body: rows,
      headStyles: { fillColor: [184, 150, 12], textColor: [44, 31, 0] },
      alternateRowStyles: { fillColor: [255, 253, 240] },
    });

    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(156, 138, 80);
      doc.text('Generated by ROTI Management System — FMB Salmiya', 14, doc.internal.pageSize.height - 10);
    }

    doc.save(`report-${selectedId}.pdf`);
  }

  return (
    <div className="space-y-5">
      <h2 className="text-xl font-bold" style={{ fontFamily: 'Amiri, serif', color: 'var(--brand-brown)', borderBottom: '1px solid var(--brand-gold-deep)', paddingBottom: '4px' }}>
        Reports & Exports
      </h2>

      <div className="bg-white rounded-xl border p-5 space-y-4" style={{ borderColor: 'var(--border-default)' }}>
        <div className="space-y-1">
          <label className="text-sm font-medium" style={{ color: 'var(--text-secondary)' }}>Select Requirement</label>
          <select value={selectedId} onChange={e => setSelectedId(e.target.value)}
            className="w-full max-w-sm border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm bg-white">
            <option value="">Choose a requirement…</option>
            {requirements.map(r => <option key={r.id} value={r.id}>{r.title} — {format(new Date(r.deliveryDate), 'dd MMM yyyy')}</option>)}
          </select>
        </div>

        {detail && (
          <>
            <div className="p-4 bg-[var(--brand-cream)] rounded-lg border" style={{ borderColor: 'var(--border-default)' }}>
              <p className="font-semibold" style={{ color: 'var(--brand-brown)' }}>{detail.title}</p>
              <div className="flex gap-4 mt-2 text-sm flex-wrap">
                <span style={{ color: 'var(--text-secondary)' }}>Required: <strong>{detail.totalPacketsRequired}</strong></span>
                <span style={{ color: 'var(--text-secondary)' }}>Committed: <strong style={{ color: 'var(--brand-gold-deep)' }}>{detail.totalCommitted || 0}</strong></span>
                <span style={{ color: 'var(--text-secondary)' }}>Commitments: <strong>{detail.commitments?.length || 0}</strong></span>
                <StatusBadge status={detail.status} />
              </div>
            </div>

            <div className="flex gap-3">
              <Button onClick={exportCSV} variant="outline" className="border-[var(--border-default)] text-[var(--brand-brown)]">
                <Download size={16} className="mr-1" /> Export CSV
              </Button>
              <Button onClick={exportPDF} className="font-semibold" style={{ background: 'var(--brand-gold)', color: 'var(--text-on-gold)' }}>
                <FileText size={16} className="mr-1" /> Export PDF
              </Button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
